//-----------------------------------------------------------------------------
// Nathan Grohoski
// CSCI-2212-01
// Program 6: A Hidden Message
//
// This program will undo the given cypher, and will read an input file 
// generated by said cypther. After undoing the bit operations the original 
// message will be printed to the file message.txt
//-----------------------------------------------------------------------------
#include "tools.hpp"

#define INF "messCypher.txt"
#define OF "message.txt"
//-----------------------------------------------------------------------------
int main( void ){
    //Print one time header
    banner();
    cout <<"        Program 6: A Hidden Message\n"
         <<"--------------------------------------------------------\n";
         
    ifstream inFile( INF );
    if( !inFile.is_open() ) fatal ("Cannot open %s for input", INF);
    ofstream outFile( OF );
    if( !outFile.is_open() ) fatal ("Cannot open %s for output", OF);
    
    unsigned char a, b, c, d, n;
    
    for(;;){
        int d = inFile.get();
        if( inFile.good() ) break;
        
        b = (d & 0x7); //b = least signif 3 bits of d 
        c = (d & 0xF8); //c = most signif 5 bits of d with LS 3 bits set to 0
        a = (c >> 3) ^ b; //undo shift and XOR with found b and c
        n = (a << 3) | b; //LS 3 bits of n = b, undo a's shift to find MS 5 bits
        
        outFile << (unsigned char)n;
    }
    
    cout << "Messaged Decypher and output to message.txt" << endl;
         
    bye();
    return 0;
}
//-----------------------------------------------------------------------------
